version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:12.18.2

commands:
  restore_node_dependencies:
    steps:
      - restore_cache:
          name: Restore node dependencies cache
          keys:
            - v1-node-dependencies-{{ checksum "package-lock.json" }}
            - v1-node-dependencies
  install_node_dependencies:
    steps:
      - run:
          name: Install node dependencies
          command: npm ci
  install_graph_cli:
    steps:
      - run:
          name: Install node dependencies
          command: sudo npm i -g --loglevel=silent --unsafe-perm=true --allow-root @graphprotocol/graph-cli
  save_node_dependencies:
    steps:
      - save_cache:
          name: Save node dependencies cache
          key: v1-node-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  deploy_develop:
    steps:
      - run:
          name: deploy rinkeby develop subgraph into public node
          command: npm run deploy-develop
  deploy_release:
    steps:
      - run:
          name: deploy rinkeby release subgraph into public node
          command: npm run deploy-release

  deploy_master:
    steps:
      - run:
          name: deploy mainnet master subgraph into public node
          command: |
            npm run deploy-master

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_node_dependencies
      - install_node_dependencies
      - save_node_dependencies
  rinkeby-develop:
    executor: default
    steps:
      - checkout
      - restore_node_dependencies
      - install_graph_cli
      - deploy_develop
  rinkeby-release:
    executor: default
    steps:
      - checkout
      - restore_node_dependencies
      - install_graph_cli
      - deploy_release
  mainnet-master:
    executor: default
    steps:
      - checkout
      - restore_node_dependencies
      - install_graph_cli
      - deploy_master

workflows:
  version: 2
  pull-request:
    jobs:
      - build
      - rinkeby-develop:
          requires:
            - build
          filters:
            branches:
              only: develop
      - rinkeby-release:
          requires:
            - build
          filters:
            branches:
              only: release
      - mainnet-master:
          requires:
            - build
          filters:
            branches:
              only: master
